version: '3'
services:
  solr:
    image: solr
    container_name: solr
    ports:
      - "8983:8983"
    volumes:
      - data:/opt/solr/server/solr/mycores
    entrypoint:
      - solr-precreate
      - movies
volumes:
  data: